discourse/discourse-global-filter

- assets/javascripts/discourse/components/global-filter-item.js
- assets/javascripts/discourse/initializers/global-filter-preference.js
- assets/javascripts/discourse/templates/components/global-filter-item.hbs
1. When routed to the home page the `active` class wasn't removed from the buttons
2. Replacing hyphens and underscores in the tag name with a space
> UX: remove active class, tag name formatting

- assets/javascripts/discourse/initializers/global-filter-preference.js
Return from initializer if no global filters are included
> Avoid infinite loop when no filters added

- assets/javascripts/discourse/components/global-filter-container.js
- assets/javascripts/discourse/templates/components/global-filter-container.hbs
- assets/javascripts/discourse/templates/components/global-filter-item.hbs
There were 3 containers with the class `global-filter-container` which was making CSS a bit difficult. This removes one, renames one, and leaves one original parent.
> DEV: too many containers with the same class name

- assets/javascripts/discourse/components/global-filter/composer-container.js
- assets/javascripts/discourse/components/global-filter/filtered-composer-tags-chooser.js
- assets/javascripts/discourse/components/global-filter/filtered-tags-chooser.js
- assets/javascripts/discourse/connectors/after-title-and-category/filtered-tags-chooser.hbs
- assets/javascripts/discourse/connectors/bread-crumbs-right/filtered-tags-chooser.hbs
- assets/javascripts/discourse/initializers/global-filter-preference.js
- assets/javascripts/discourse/templates/components/global-filter/composer-container.hbs
- assets/javascripts/discourse/templates/components/global-filter/filtered-composer-tags-chooser.hbs
- assets/javascripts/discourse/templates/components/global-filter/filtered-tags-chooser.hbs
- assets/stylesheets/common/global-filter.scss
- plugin.rb
> viewing /tag/GLOBAL_FILTER
> viewing /tags/intersection/GLOBAL_FILTER/cloud
> see that we can create a topic with a global-filter-tag, and not have that value show up in the tag-chooser. Even though the attached GFT does not show up in the select-kit preview, it does persist on topic creation.
> Hide GTF values from tag-chooser

- assets/javascripts/discourse/initializers/global-filter-preference.js
- assets/stylesheets/common/global-filter.scss
- test/javascripts/components/global-filter-item-test.js
- test/javascripts/components/global-filter/composer-item-test.js
This is a partial revert of https://github.com/discourse/discourse-global-filter/pull/12. We do need to keep the active class, even if the view is the homepage because the homepage content is going to be filtered by the default global filter. cc @awesomerobot
> FIX: Keep global filter button active class

- assets/javascripts/discourse/components/global-filter/composer-item.js
- assets/javascripts/discourse/templates/components/global-filter/composer-item.hbs
- Displays labels without - or _ 
- Simplifies HTML a bit and adds an empty `.pre-label` element which makes it easier to add icons in a theme
> UX: Minor adjustments to composer checkboxes

- app/controllers/filter_tags_controller.rb
- app/models/filter_tag.rb
- assets/javascripts/discourse/components/global-filter/composer-container.js
- assets/javascripts/discourse/components/global-filter/composer-item.js
- assets/javascripts/discourse/initializers/global-filter-preference.js
- lib/category_list_serializer_extension.rb
- plugin.rb
- test/javascripts/acceptance/global-filter-preference-test.js
- test/javascripts/components/global-filter/composer-item-test.js
This gives the ability to "hot reload" the composer category-dropdown options with the filtered categories, per GFT. 
- In the case multiple are selected, we combine the list of categories in the options.
- In the case no GFT is selected we keep the category options of the **last previously selected** GFT
> Replace composer category options when selecting a new filter-item

- assets/javascripts/discourse/controllers/admin-plugins-filter-tag.js
- assets/stylesheets/common/global-filter.scss
When choosing categories in the admin UI, the selected list would not update in real time if a category had a parent included behind the scenes. This is fixed in this pr. 
Fix bad admin ui on small screens.
> Fix admin ui styles / category display

- assets/javascripts/discourse/initializers/filtered-categories-for-global-filter.js
- assets/javascripts/discourse/initializers/global-filter-preference.js
- assets/javascripts/discourse/initializers/set-category-drop-options.js
- assets/javascripts/discourse/templates/components/global-filter/filtered-tags-chooser.hbs
- plugin.rb
- test/javascripts/components/global-filter-container-test.js
- test/javascripts/components/global-filter-item-test.js
- test/javascripts/components/global-filter/filtered-tags-chooser-test.js
Category dropdown options (categories) were not being filtered properly and we would display the same list of options for both the category and subcategory dropdowns.
Move the logic required to set the content of category & subcategory dropdown from `discourse/initializers/global-filter-preference.js` to its own initializer. This gets us a few things:
- Scopes category dropdown manipulations to intended dropdowns
- Removes extra (unnecessary) ajax calls on all routes
- Cleans up the `global-filter-preference` initializer
> Filter category and subcategory dropdowns by GFT

- assets/javascripts/discourse/components/global-filter/filter-item.js
This PR makes the filter dropdown's trigger button's label a `@tracked` property so that it can easily be overridden by themes seeking custom labelling.
> DEV: Make `spacedTag` a `@tracked` property for easy override

- assets/javascripts/discourse/components/global-filter/composer-container.js
- assets/javascripts/discourse/components/global-filter/composer-item.js
It's more "the Ember way" and makes it a tiny bit easier to override if/when needed.
This also fixes a linting issue in composer-container.js
> REFACTOR: Use a getter for a composer item property

- jobs/scheduled/update_category_stats.rb
- lib/category_detailed_serializer_extension.rb
- plugin.rb
This PR adds `posts_week` data for categories and subcategories with global filters.
> DEV: Serialize posts per week data

- assets/javascripts/discourse/components/global-filter/filter-item.js
- test/javascripts/acceptance/global-filter-context-test.js
- test/javascripts/acceptance/global-filter-preference-test.js
- test/javascripts/acceptance/require-tag-on-topic-creation-test.js
- test/javascripts/acceptance/set-category-drop-options-test.js
- test/javascripts/components/global-filter-container-test.js
- test/javascripts/components/global-filter-item-test.js
- test/javascripts/components/global-filter/composer-container-test.js
- test/javascripts/components/global-filter/composer-item-test.js
- test/javascripts/components/global-filter/filtered-tags-chooser-test.js
As per [Meta request](https://meta.discourse.org/t/epic-ongoing-work-tracker/216708/481?u=keegan), this PR updates appearance of the topic count on filter tags so they are rendered based on locale (typically with commas).
So that `427075` is rendered as `427,075`
> UX: Tag topic count should be comma separated

- assets/javascripts/discourse/components/category-matrix-checkbox.js
When no category ids are present on a global filter,`this.filterTag.category_ids` returns `""`.  When trying to map and split this empty string to convert the possible string values to integers we do
```
.map((str) => Number(str));
```
The problem was that `Number("")` evaluates to `0`. This broke our topic filtering logic as you could not leave the category_ids section blank for a Global Filter, it was always assigning `0` at the minimum. This did not allow for the _Leave every checkbox blank to select all categories_ functionality.
> FIX: Regression on category matrix selections

- assets/javascripts/discourse/components/global-filter-container.hbs
- assets/javascripts/discourse/components/global-filter/filter-item.hbs
This PR updates the usage of the plugin outlet component to get rid of the deprecation warning:
```js
Deprecation notice: PluginOutlet arguments should now be passed using `@outletArgs=` instead of `@args=` (outlet: below-global-filter-item) [deprecation id: discourse.plugin-outlet-args]
```
> DEV: Update plugin outlet declaration

- assets/javascripts/select-kit/addon/components/global-filter-chooser-row.js
- assets/javascripts/select-kit/addon/components/global-filter-chooser.js
**This PR updates the plugin to have some minor fixes to improve overriding in themes.**
Specifically it:
- Ensures `site` object is defined before checking for global filters (not doing this results in undefined errors when using `modifyClass()` in themes/components)
- Simplifies assigning `alternate_name` for tag names with alternate names. There is no need to find and filter the `site.global_filters` for the current item since the `item` object is already present with its data.
> FIX: Minor fixes to improve overriding in themes 

- plugin.rb
- Add custom `CategoryDetailed` serializer method to pass the latest topics per category, per global_filter. This will be utilized to add custom topic previews per category.
- Only return 5 topics by default.
> DEV: Add custom `recent_category_topics_for_filter_tag` `CategoryDetailed` serializer method

- plugin.rb
Improve performance by simplifying the `most_recent_unpinned_category_topic_for_filter_tag` serializer method and only getting the first topic.
> DEV: Replace `recent_category_topics_for_filter_tag` with `most_recent_unpinned_category_topic_for_filter_tag`

- assets/javascripts/discourse/components/global-filter/filtered-tags-chooser.hbs
This PR adds plugin outlets to the `<FilteredTagsChooser />` component for easy customization.
> DEV: Add plugin outlets inside `filtered-tags-chooser` component

- assets/javascripts/discourse/connectors/inline-extra-nav-item/filtered-tags-chooser.hbs
- assets/stylesheets/common/global-filter.scss
This PR takes advantage of the new [plugin outlet `inline-extra-nav-item`](https://github.com/discourse/discourse/pull/21437) to move the filtered tag chooser outside of the dropdown and next to it instead.
**Before:**
**After:**
> DEV: On mobile show tags chooser outside the dropdown

- assets/javascripts/discourse/initializers/global-filter-preference.js
- test/javascripts/acceptance/global-filter-preference-test.js
`/login` is going into an infinite loop if the categories list is set as default homepage.
This PR fixes it by not aborting the current transition and only redirecting on the `next` cycle.
It also fixes a test failure that has been happening for [~2 months.](https://github.com/discourse/discourse-global-filter/actions)
For reference, the removed `transition.abort()` call was probably intended as a workaround for this (still open) Ember issue: https://github.com/emberjs/ember.js/issues/18577
> FIX: /login loop when categories is default homepage

- assets/javascripts/discourse/components/global-filter/header.js
- assets/javascripts/discourse/initializers/global-filter-preference.js
- test/javascripts/acceptance/global-filter-preference-test.js
When we navigate to a `/new-topic` route with `tags` query params, we may be on the topic creation flow for a given global filter but we weren't navigating to it.
This PR sets the preferred global filter for the current user by inferring it from the passed `tags`:
* if one of the tags in `tags` is an existing global filter
* if one of the tags in `tags` is a child to an existing global filter
> FIX: infer global filter from /new-topic tags query param

- assets/javascripts/discourse/initializers/global-filter-preference.js
- test/javascripts/components/global-filter/composer-item-test.js
If a child of a global filter tag is used on `/new-topic?tags=x`, add the parent tag to the list.
> FIX: add parent global filter tag on /new-topic

- assets/javascripts/discourse/initializers/apply-global-filter-styles.js
- assets/javascripts/discourse/initializers/global-filter-preference.js
- test/javascripts/acceptance/global-filter-preference-test.js
This is very hard to test, it was happening very intermittently:
* When visiting `/new-topic` with category and tags params, _sometimes_ it would render the wrong app, the 1st option instead of the one inferred from the tags param
* When visiting `/` or `/categories` after having visited a different global filter (which is stored as a preference), the presented data would be from the preferred app, but the "visually" selected app was the 1st option in the list
> FIX: routing on /new-topic and /categories

- assets/javascripts/discourse/initializers/apply-global-filter-styles.js
`router:main` is private and has an unstable API (e.g. the `didTransition` event does not fire in Ember 5)
> DEV: Update to use public router service

- spec/requests/categories_controller_spec.rb
`Guardian.anon` was removed here https://github.com/discourse/discourse/pull/24705. 
The `anon` word is overloaded, so we're replacing it with something more explicit.
> DEV: Update test guardian due to core change

- jobs/scheduled/update_category_stats.rb
- spec/jobs/update_category_stats_spec.rb
We are currently seeing the following error at `update_category_stats.rb:20`
```
Job exception: undefined method `id' for nil:NilClass
```
This PR exits the job early if there are no tags, and only runs the updates through tags that exist.
Ideally, more tests can be added later for the job.
> FIX: Don't error out when the tag in settings doesn't exist

- assets/javascripts/discourse/components/global-filter/composer-container.js
- assets/javascripts/discourse/components/global-filter/filtered-composer-tags-chooser.js
- assets/javascripts/select-kit/addon/components/global-filter-chooser.js
Include children filters when listing the hidden tags on `FilteredComposerTagsChooser`, so they're not selectable via the tag chooser.
Also removed `site`, `siteSettings`, `tagParam`, and `globalFilters` from `ComposerContainer` as they aren't used.
> FEATURE: include children filters on hidden tags

- test/javascripts/acceptance/global-filter-preference-test.js
Now that passkeys are default enabled, the `/login` modal triggers a challenge request that needs to be mocked.
> DEV: Add missing passkeys challenge pretender

- spec/serializers/filter_tag_index_serializer_spec.rb
We shouldn't need to strictly match the order of the filter tags.
```
Failures:
1) GlobalFilter::FilterTagIndexSerializer includes categories for filter_tags
Failure/Error:
expect(filter_tag_response[:categories].pluck(:id)).to eq(
filter_tag[:category_ids].split("|").map(&:to_i),
)
expected: [49, 50]
got: [50, 49]
(compared using ==)
```
> DEV: Match an unordered array

- assets/javascripts/discourse/initializers/set-category-drop-options.js
- assets/javascripts/discourse/services/global-filter.js
This commit changes how the call to the API `modifySelectKit.replaceContent` is made
when replacing the content of the category drop, to remove it from inside a Promise.
This ensures the API call is made in the expected order and allows further customization down
the initialization pipeline.
> DEV: Removed async API call to modifySelectKit.replaceContent

- jobs/scheduled/update_category_stats.rb
Internal: /t/135393
The `update_category_stats` job was failing due to a bad lookup of `topics` on the `Post` model.
This PR updates the job to lookup topics by `topic_id`.
> FIX: `update_category_stats` erroring on bad column lookup

- assets/javascripts/discourse/components/global-filter/filtered-tags-composer-chooser.gjs
- assets/javascripts/discourse/connectors/after-title-and-category/filtered-tags-chooser.gjs
- assets/stylesheets/common/global-filter.scss
This filtered tag chooser was accidentally removed in https://github.com/discourse/discourse-global-filter/pull/153. This PR adds it back.
> DEV: Add back `FilteredTagsComposerChooser`

- assets/javascripts/discourse/initializers/global-filter-preference.js
- spec/system/global_filter_routing_spec.rb
- spec/system/scrolls_correctly_in_categories_spec.rb
- test/javascripts/acceptance/global-filter-preference-test.js
For some reason, the `transitionTo` would make the `scrollManager` bug out and not scroll to the top of the page.
This PR solves that and adds a test to ensure we do not have regressions
> FIX: Solve scrolling issue in categories
